name: GitHub Actions Deployment
on:
  push:
    branches:
      - main
      - publish

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install Dependencies & Build
        run: |
          npm ci
          npm run build

      - name: Deploy to Github Stages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist

  publish:
    runs-on: ubuntu-latest
    if: github.ref_name == 'publish'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install Dependencies & Build
        run: |
          npm ci
          npm run build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        server:
          server: ${{ secrets.host }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          port: $PORT
          protocol: ftps
          local-dir: dist
